### ISSUE TITLE
Add NSTableView support to hs._asm.guitk

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hs._asm.guitk#1]
I have some relatively complicated UI's that are currently created using HTML and a `hs.webview`, however it would be awesome if I could use `hs._asm.guitk` instead.

Is adding `NSTableView` support to `hs._asm.guitk` a remote possibility?

<img width="1112" alt="screen shot 2018-12-16 at 1 03 54 pm" src="https://user-images.githubusercontent.com/22286696/50049202-2fe4e280-0133-11e9-9c5c-77582fdad185.png">

**Comment by latenitefilms** [comment]
FWIW - this is probably less of a priority now, as `hs.webview`'s are actually working pretty well for our purposes.

**Comment by asmagill** [comment]
Well, the guitk is still on my "I'd like to finish it someday" list...

I have this wacky notion of (eventually and not anytime soon) being able to create the console window, application menus, preferences panel, and about box *entirely* from Lua... and then if that wasn't enough of a pipe dream, maybe allowing for the ability to replicate the core application, change a few settings (like the bundleID and such) and then use "Hammerspoon" as an engine for creating entirely self contained and separate "Applications" effectively coded entirely in Lua.

We're nowhere near that and may never be... but I think it'd be a cool idea.

At any rate, I'm going to leave this open for now as a reminder to myself about the kind of interfaces we'll be able to create when additional view types are supported.

**Comment by latenitefilms** [comment]
Well, that's essentially what [CommandPost-App](https://github.com/CommandPost/CommandPost-App) is - it's essentially just doing a find and replace (i.e. replace "Hammerspoon" with "CommandPost"), then the only other real additions are hiding items in the menubar, and merging any code that hasn't quite made it to Hammerspoon yet. This would definitely be something I'd be very keen to help with.

FWIW - If I had to make a priority wish-list of all the amazing things you've working on, it would look something like this:

1. **`hs.axuielement` - Accessing Accessibility Objects with Hammerspoon hammerspoon/hammerspoon#1630**
We've been using `hs._asm.axuielement` solidly for a few years now, and it's fricken awesome. It's been rock solid for us, and such an important and useful extension. I'd love to see this finally added to the Hammerspoon core, so that others can start using it, and also offer ideas, suggestions and pull requests.

2. **`hs.preferences` - Property List Editor with NSKeyedArchiver support hammerspoon/hammerspoon#1498**
There's quite a few issues and pull requests all tackling Property Lists & Defaults, so it would be great to finally consolidate and solve this feature requests for v1.0 as well. We currently use a mixture of `hs.plist`, `hs._asm.cfpreferences` and our own `cp.plist`. This would mean we could also finally finish up [`hs.notdisturbmode`](https://github.com/Hammerspoon/hammerspoon/pull/1706).

3. **`hs.touchbar` - Add Extension for Touch Bar Support hammerspoon/hammerspoon#1078**
We've been using `hs._asm.undocumented.touchbar` for ages now - it's also awesome and rock solid. I reckon this is probably ready to merge into Hammerspoon too?

4. **`hs.text` -  Module to handle different string encodings hammerspoon/hammerspoon#2215**

5. Add "non activating" option to Console hammerspoon/hammerspoon#2078

**Comment by asmagill** [comment]
Yeah, I kind of realized that after I submitted it, but in my ideal vision, I’d like it if you didn’t have to recompile; more like python using GTK bindings or tkinter. Though TBH I’m not entirely sure how feasible (or hard, requiring things we’ve avoided like kexts or privileged helpers, etc.) this might become with Apple’s increasing penchant for locking things down...

And you currently inherit the console (and other items, like the menus, etc.)... what if you wanted to fully suppress it? Or have one window that just showed log messages while another acted like the current console but without extraneous output (I.e. nothing that didn’t come from the ‘print’ command in your own code)? With the full UI implemented in Lua, these become possible *without* requiring recompilation or deviation from the master branch.

At any rate, it’s just one possible vision for Hammerspoon’s future; it’s useful to me now as it is so I’ll keep contributing and we’ll see where things go as my and your and others contributions get added!

**Comment by asmagill** [comment]
I’ll comment further on the wish list tomorrow (I need to try and get some sleep) but your list isn’t that different from mine, though I still have some concerns re touchbar... maybe if I enumerate them we can come up with a way for you to help test and/or address them.

**Comment by asmagill** [comment]
Closing this; replacing module with newer version named `hs._asm.uitk` (yeah, similar name, but different (1) so I can keep them distinct in my mind and (2) the organizational structure has changed a little...)

NSTableView isn't added yet, but *is* on the list of things I plan to add soon.
